name: 'Deploy to Netlify'

on:
  push:
    branches:
    - master

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build the website
        run: |
          mkdir -p /home/runner/work/_temp/_github_home/build
          <commands_to_build_the_site_and_store_the_output_in_'/home/runner/work/_temp/_github_home/build'>
      - name: Deploy Netlify
        uses: danakim/gh-action-deploy-netlify@master
        with:
          AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          DEPLOY_PROD: true
